#!/usr/bin/env bash
set -euo pipefail

# Export SQL Server metrics in Prometheus text format
# Run every 60 seconds via cron
# Output: /var/opt/mssql/backup/metrics/metrics.prom

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${SCRIPT_DIR}/../helpers/load_config.sh"

METRICS_DIR="/var/opt/mssql/backup/metrics"
METRICS_FILE="${METRICS_DIR}/metrics.prom"
TEMP_FILE="${METRICS_DIR}/.metrics.prom.tmp"

mkdir -p "$METRICS_DIR"

run_query() {
    sqlcmd -S "$SERVER_CONN" -U "$SQL_USER" -P "$SQL_PASSWORD" ${SQLCMD_ENCRYPT_FLAGS} \
        -h -1 -W -Q "$1" 2>/dev/null | tr -d ' ' | head -1
}

cat > "$TEMP_FILE" << 'HEADER'
# Hospital Database Backup — Prometheus Metrics
# Generated by export_metrics.sh

HEADER

# ─── Backup Health ───
LAST_FULL=$(run_query "SELECT ISNULL(DATEDIFF(SECOND, '19700101', MAX(backup_finish_date)),0) FROM msdb.dbo.backupset WHERE database_name='HospitalBackupDemo' AND type='D'" || echo "0")
LAST_DIFF=$(run_query "SELECT ISNULL(DATEDIFF(SECOND, '19700101', MAX(backup_finish_date)),0) FROM msdb.dbo.backupset WHERE database_name='HospitalBackupDemo' AND type='I'" || echo "0")
LAST_LOG=$(run_query "SELECT ISNULL(DATEDIFF(SECOND, '19700101', MAX(backup_finish_date)),0) FROM msdb.dbo.backupset WHERE database_name='HospitalBackupDemo' AND type='L'" || echo "0")
FULL_SIZE=$(run_query "SELECT ISNULL(MAX(backup_size),0) FROM msdb.dbo.backupset WHERE database_name='HospitalBackupDemo' AND type='D'" || echo "0")
FULL_DURATION=$(run_query "SELECT ISNULL(DATEDIFF(SECOND, MAX(backup_start_date), MAX(backup_finish_date)),0) FROM msdb.dbo.backupset WHERE database_name='HospitalBackupDemo' AND type='D'" || echo "0")

cat >> "$TEMP_FILE" << EOF
# HELP hospital_backup_last_success_timestamp Unix timestamp of last successful backup
# TYPE hospital_backup_last_success_timestamp gauge
hospital_backup_last_success_timestamp{type="full"} ${LAST_FULL}
hospital_backup_last_success_timestamp{type="differential"} ${LAST_DIFF}
hospital_backup_last_success_timestamp{type="log"} ${LAST_LOG}

# HELP hospital_backup_size_bytes Size of last backup in bytes
# TYPE hospital_backup_size_bytes gauge
hospital_backup_size_bytes{type="full"} ${FULL_SIZE}

# HELP hospital_backup_duration_seconds Duration of last backup
# TYPE hospital_backup_duration_seconds gauge
hospital_backup_duration_seconds{type="full"} ${FULL_DURATION}

EOF

# Verification status
VERIFY_OK=$(run_query "SELECT CASE WHEN EXISTS(SELECT 1 FROM HospitalBackupDemo.dbo.BackupVerificationLog WHERE Status='PASS' AND VerificationStart>=DATEADD(DAY,-1,GETDATE())) THEN 1 ELSE 0 END" || echo "0")
cat >> "$TEMP_FILE" << EOF
# HELP hospital_backup_verification_status 1=pass 0=fail in last 24h
# TYPE hospital_backup_verification_status gauge
hospital_backup_verification_status ${VERIFY_OK}

EOF

# ─── Database Availability ───
DB_UP=$(run_query "SELECT CASE WHEN state=0 THEN 1 ELSE 0 END FROM sys.databases WHERE name='HospitalBackupDemo'" || echo "0")
CONNECTIONS=$(run_query "SELECT COUNT(*) FROM sys.dm_exec_sessions WHERE database_id=DB_ID('HospitalBackupDemo')" || echo "0")
LOG_USED=$(run_query "SELECT CAST(ROUND(CAST(cntr_value AS FLOAT),0) AS INT) FROM sys.dm_os_performance_counters WHERE counter_name='Percent Log Used' AND instance_name='HospitalBackupDemo'" || echo "0")
DEADLOCKS=$(run_query "SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name='Number of Deadlocks/sec' AND instance_name='_Total'" || echo "0")
LONG_QUERIES=$(run_query "SELECT COUNT(*) FROM sys.dm_exec_requests WHERE database_id=DB_ID('HospitalBackupDemo') AND total_elapsed_time>300000" || echo "0")

cat >> "$TEMP_FILE" << EOF
# HELP hospital_db_up 1=online 0=offline
# TYPE hospital_db_up gauge
hospital_db_up ${DB_UP}

# HELP hospital_db_active_connections Current active connections
# TYPE hospital_db_active_connections gauge
hospital_db_active_connections ${CONNECTIONS}

# HELP hospital_db_transaction_log_used_percent Transaction log usage
# TYPE hospital_db_transaction_log_used_percent gauge
hospital_db_transaction_log_used_percent ${LOG_USED}

# HELP hospital_db_deadlocks_total Cumulative deadlock count
# TYPE hospital_db_deadlocks_total counter
hospital_db_deadlocks_total ${DEADLOCKS}

# HELP hospital_db_long_running_queries Queries running > 5 minutes
# TYPE hospital_db_long_running_queries gauge
hospital_db_long_running_queries ${LONG_QUERIES}

EOF

# ─── Security Events ───
FAILED_LOGINS=$(run_query "SELECT ISNULL(COUNT(*),0) FROM HospitalBackupDemo.dbo.SecurityEvents WHERE EventType='Login Failed' AND EventDate>=DATEADD(HOUR,-1,GETDATE())" || echo "0")
TDE_STATUS=$(run_query "SELECT CASE WHEN encryption_state=3 THEN 1 ELSE 0 END FROM sys.dm_database_encryption_keys WHERE database_id=DB_ID('HospitalBackupDemo')" || echo "0")
CERT_EXPIRY_DAYS=$(run_query "SELECT ISNULL(DATEDIFF(DAY,GETDATE(),MAX(expiry_date)),0) FROM master.sys.certificates WHERE name LIKE 'HospitalBackupDemo_TDE%'" || echo "0")
AUDIT_ROWS=$(run_query "SELECT COUNT(*) FROM HospitalBackupDemo.dbo.AuditLog" || echo "0")

cat >> "$TEMP_FILE" << EOF
# HELP hospital_security_failed_logins_per_hour Failed logins in last hour
# TYPE hospital_security_failed_logins_per_hour gauge
hospital_security_failed_logins_per_hour ${FAILED_LOGINS}

# HELP hospital_security_tde_status 1=encrypted 0=not
# TYPE hospital_security_tde_status gauge
hospital_security_tde_status ${TDE_STATUS}

# HELP hospital_security_cert_days_until_expiry Days until TDE cert expires
# TYPE hospital_security_cert_days_until_expiry gauge
hospital_security_cert_days_until_expiry ${CERT_EXPIRY_DAYS}

# HELP hospital_security_audit_log_rows_total Total audit log entries
# TYPE hospital_security_audit_log_rows_total counter
hospital_security_audit_log_rows_total ${AUDIT_ROWS}
EOF

# Atomic write
mv "$TEMP_FILE" "$METRICS_FILE"
