#!/usr/bin/env bash
set -euo pipefail

# Generate completely fake test data for development database
# HIPAA 45 CFR 164.514(b): No PHI in dev environments
# Output: phases/phase1-database/data/fake/*.sql

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${SCRIPT_DIR}/../helpers/load_config.sh"

FAKE_DIR="${PROJECT_ROOT}/phases/phase1-database/data/fake"
mkdir -p "$FAKE_DIR"

echo -e "${BLUE}=== Fake Data Generator (NO PHI) ===${NC}"
echo "Output: ${FAKE_DIR}/"
echo ""

# Arrays for random data generation
FIRST_NAMES=("TestAlice" "TestBob" "TestCarol" "TestDave" "TestEve" "TestFrank"
             "TestGrace" "TestHenry" "TestIvy" "TestJack" "TestKate" "TestLeo"
             "TestMia" "TestNick" "TestOlive" "TestPaul" "TestQuinn" "TestRose"
             "TestSam" "TestTina" "TestUma" "TestVic" "TestWen" "TestXia"
             "TestYuri" "TestZara")

LAST_NAMES=("FakeSmith" "FakeJones" "FakeBrown" "FakeWilson" "FakeTaylor"
            "FakeDavis" "FakeMiller" "FakeClark" "FakeHall" "FakeYoung"
            "FakeKing" "FakeWright" "FakeLee" "FakeWalker" "FakeHarris")

DEPARTMENTS=("Emergency" "Cardiology" "Neurology" "Pediatrics" "Oncology"
             "Orthopedics" "Dermatology" "Radiology" "Pathology" "Psychiatry")

DIAGNOSES=("Test Hypertension" "Test Diabetes Type 2" "Test Fracture" "Test Bronchitis"
           "Test Allergic Rhinitis" "Test Migraine" "Test Anemia" "Test UTI"
           "Test Back Pain" "Test Gastritis")

MEDICATIONS=("TestMed-A 10mg" "TestMed-B 500mg" "TestMed-C 250mg" "TestMed-D 100mg"
             "TestMed-E 50mg" "TestMed-F 20mg" "TestMed-G 5mg" "TestMed-H 200mg")

random_element() {
    local arr=("$@")
    echo "${arr[$((RANDOM % ${#arr[@]}))]}"
}

# Generate Patients (150 records)
echo "Generating fake patients..."
cat > "${FAKE_DIR}/fake_patients.sql" << 'SQLHEADER'
-- Fake patient data for development — NO PHI
-- Generated by generate_fake_data.sh
USE HospitalBackupDemo_Dev;
GO
SET NOCOUNT ON;
SQLHEADER

for i in $(seq 1 150); do
    FNAME=$(random_element "${FIRST_NAMES[@]}")
    LNAME=$(random_element "${LAST_NAMES[@]}")
    NID=$(printf "DEV%09d" $i)
    YEAR=$((1950 + RANDOM % 50))
    MONTH=$((1 + RANDOM % 12))
    DAY=$((1 + RANDOM % 28))
    GENDER=$( [ $((RANDOM % 2)) -eq 0 ] && echo "M" || echo "F" )

    cat >> "${FAKE_DIR}/fake_patients.sql" << EOF
INSERT INTO dbo.Patients (PatientCode, FirstName, LastName, NationalID, DateOfBirth, Gender, Phone, Address)
VALUES ('PDEV${i}', '${FNAME}', '${LNAME}', '${NID}', '${YEAR}-$(printf '%02d' $MONTH)-$(printf '%02d' $DAY)', '${GENDER}', '0000000000', 'Dev Test Address ${i}');
EOF
done
echo "GO" >> "${FAKE_DIR}/fake_patients.sql"
echo -e "  ${GREEN}✓${NC} fake_patients.sql (150 records)"

# Generate Doctors (150 records)
echo "Generating fake doctors..."
cat > "${FAKE_DIR}/fake_doctors.sql" << 'SQLHEADER'
-- Fake doctor data for development — NO PHI
USE HospitalBackupDemo_Dev;
GO
SET NOCOUNT ON;
SQLHEADER

for i in $(seq 1 150); do
    FNAME=$(random_element "${FIRST_NAMES[@]}")
    LNAME=$(random_element "${LAST_NAMES[@]}")
    DEPT=$(random_element "${DEPARTMENTS[@]}")

    cat >> "${FAKE_DIR}/fake_doctors.sql" << EOF
INSERT INTO dbo.Doctors (DoctorCode, FirstName, LastName, Specialization, Phone, Email)
VALUES ('DDEV${i}', 'Dr${FNAME}', '${LNAME}', '${DEPT}', '0000000000', 'dr${i}@dev.hospital.local');
EOF
done
echo "GO" >> "${FAKE_DIR}/fake_doctors.sql"
echo -e "  ${GREEN}✓${NC} fake_doctors.sql (150 records)"

# Generate Medical Records (150 records)
echo "Generating fake medical records..."
cat > "${FAKE_DIR}/fake_medical_records.sql" << 'SQLHEADER'
-- Fake medical records for development — NO PHI
USE HospitalBackupDemo_Dev;
GO
SET NOCOUNT ON;
SQLHEADER

for i in $(seq 1 150); do
    PATIENT_ID=$((1 + RANDOM % 150))
    DOCTOR_ID=$((1 + RANDOM % 150))
    DIAG=$(random_element "${DIAGNOSES[@]}")
    YEAR=2025
    MONTH=$((1 + RANDOM % 12))
    DAY=$((1 + RANDOM % 28))

    cat >> "${FAKE_DIR}/fake_medical_records.sql" << EOF
INSERT INTO dbo.MedicalRecords (RecordNumber, PatientID, DoctorID, Diagnosis, VisitType, VisitDate, Notes)
VALUES ('RDEV${i}', ${PATIENT_ID}, ${DOCTOR_ID}, '${DIAG}', 'Outpatient', '${YEAR}-$(printf '%02d' $MONTH)-$(printf '%02d' $DAY)', 'Dev test notes for record ${i}');
EOF
done
echo "GO" >> "${FAKE_DIR}/fake_medical_records.sql"
echo -e "  ${GREEN}✓${NC} fake_medical_records.sql (150 records)"

# Generate Prescriptions (150 records)
echo "Generating fake prescriptions..."
cat > "${FAKE_DIR}/fake_prescriptions.sql" << 'SQLHEADER'
-- Fake prescriptions for development — NO PHI
USE HospitalBackupDemo_Dev;
GO
SET NOCOUNT ON;
SQLHEADER

for i in $(seq 1 150); do
    PATIENT_ID=$((1 + RANDOM % 150))
    DOCTOR_ID=$((1 + RANDOM % 150))
    MED=$(random_element "${MEDICATIONS[@]}")
    STATUS=$( [ $((RANDOM % 3)) -eq 0 ] && echo "Completed" || echo "Active" )

    cat >> "${FAKE_DIR}/fake_prescriptions.sql" << EOF
INSERT INTO dbo.Prescriptions (PrescriptionNumber, PatientID, DoctorID, Status, Notes)
VALUES ('RXDEV${i}', ${PATIENT_ID}, ${DOCTOR_ID}, '${STATUS}', 'Dev test prescription ${i}');
EOF
done
echo "GO" >> "${FAKE_DIR}/fake_prescriptions.sql"
echo -e "  ${GREEN}✓${NC} fake_prescriptions.sql (150 records)"

echo ""
echo -e "${GREEN}✓ Fake data generated in: ${FAKE_DIR}/${NC}"
echo ""
echo "To load into dev database:"
echo "  APP_ENV=development ./scripts/helpers/run_sql.sh ${FAKE_DIR}/fake_patients.sql HospitalBackupDemo_Dev"
